services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medcom-dev-db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - medcom_postgres_data:/var/lib/postgresql/data
    networks:
      - medcom-network

volumes:
  medcom_postgres_data:
    name: medcom_postgres_data

networks:
  medcom-network:
