package com.pharmaresolve.medcom.domain;

import static com.pharmaresolve.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AppConnectionLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConnectionLogAllPropertiesEquals(AppConnectionLog expected, AppConnectionLog actual) {
        assertAppConnectionLogAutoGeneratedPropertiesEquals(expected, actual);
        assertAppConnectionLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConnectionLogAllUpdatablePropertiesEquals(AppConnectionLog expected, AppConnectionLog actual) {
        assertAppConnectionLogUpdatableFieldsEquals(expected, actual);
        assertAppConnectionLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConnectionLogAutoGeneratedPropertiesEquals(AppConnectionLog expected, AppConnectionLog actual) {
        assertThat(expected)
            .as("Verify AppConnectionLog auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConnectionLogUpdatableFieldsEquals(AppConnectionLog expected, AppConnectionLog actual) {
        assertThat(expected)
            .as("Verify AppConnectionLog relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getTime()).as("check time").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getTime()))
            .satisfies(e -> assertThat(e.getIpAddress()).as("check ipAddress").isEqualTo(actual.getIpAddress()))
            .satisfies(e -> assertThat(e.getUserAgent()).as("check userAgent").isEqualTo(actual.getUserAgent()))
            .satisfies(e -> assertThat(e.getLatitude()).as("check latitude").isEqualTo(actual.getLatitude()))
            .satisfies(e -> assertThat(e.getLongitude()).as("check longitude").isEqualTo(actual.getLongitude()))
            .satisfies(e -> assertThat(e.getSessionDuration()).as("check sessionDuration").isEqualTo(actual.getSessionDuration()))
            .satisfies(e ->
                assertThat(e.getPreviousLoginTime())
                    .as("check previousLoginTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getPreviousLoginTime())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConnectionLogUpdatableRelationshipsEquals(AppConnectionLog expected, AppConnectionLog actual) {
        assertThat(expected)
            .as("Verify AppConnectionLog relationships")
            .satisfies(e -> assertThat(e.getAppUser()).as("check appUser").isEqualTo(actual.getAppUser()))
            .satisfies(e -> assertThat(e.getPharmacy()).as("check pharmacy").isEqualTo(actual.getPharmacy()));
    }
}
