package com.pharmaresolve.medcom.domain;

import static com.pharmaresolve.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class NotificationPreferenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceAllPropertiesEquals(NotificationPreference expected, NotificationPreference actual) {
        assertNotificationPreferenceAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationPreferenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceAllUpdatablePropertiesEquals(
        NotificationPreference expected,
        NotificationPreference actual
    ) {
        assertNotificationPreferenceUpdatableFieldsEquals(expected, actual);
        assertNotificationPreferenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceAutoGeneratedPropertiesEquals(
        NotificationPreference expected,
        NotificationPreference actual
    ) {
        assertThat(expected)
            .as("Verify NotificationPreference auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceUpdatableFieldsEquals(NotificationPreference expected, NotificationPreference actual) {
        assertThat(expected)
            .as("Verify NotificationPreference relevant properties")
            .satisfies(e -> assertThat(e.getEmailEnabled()).as("check emailEnabled").isEqualTo(actual.getEmailEnabled()))
            .satisfies(e -> assertThat(e.getSmsEnabled()).as("check smsEnabled").isEqualTo(actual.getSmsEnabled()))
            .satisfies(e -> assertThat(e.getPushEnabled()).as("check pushEnabled").isEqualTo(actual.getPushEnabled()))
            .satisfies(e ->
                assertThat(e.getQuietHoursStart())
                    .as("check quietHoursStart")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getQuietHoursStart())
            )
            .satisfies(e ->
                assertThat(e.getQuietHoursEnd())
                    .as("check quietHoursEnd")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getQuietHoursEnd())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceUpdatableRelationshipsEquals(
        NotificationPreference expected,
        NotificationPreference actual
    ) {
        // empty method
    }
}
