package com.pharmaresolve.medcom.domain;

import static com.pharmaresolve.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PharmacyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPharmacyAllPropertiesEquals(Pharmacy expected, Pharmacy actual) {
        assertPharmacyAutoGeneratedPropertiesEquals(expected, actual);
        assertPharmacyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPharmacyAllUpdatablePropertiesEquals(Pharmacy expected, Pharmacy actual) {
        assertPharmacyUpdatableFieldsEquals(expected, actual);
        assertPharmacyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPharmacyAutoGeneratedPropertiesEquals(Pharmacy expected, Pharmacy actual) {
        assertThat(expected)
            .as("Verify Pharmacy auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPharmacyUpdatableFieldsEquals(Pharmacy expected, Pharmacy actual) {
        assertThat(expected)
            .as("Verify Pharmacy relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()))
            .satisfies(e -> assertThat(e.getTimeZone()).as("check timeZone").isEqualTo(actual.getTimeZone()))
            .satisfies(e -> assertThat(e.getWebsite()).as("check website").isEqualTo(actual.getWebsite()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()))
            .satisfies(e ->
                assertThat(e.getCreated()).as("check created").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getCreated())
            )
            .satisfies(e -> assertThat(e.getActivatedBy()).as("check activatedBy").isEqualTo(actual.getActivatedBy()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPharmacyUpdatableRelationshipsEquals(Pharmacy expected, Pharmacy actual) {
        assertThat(expected)
            .as("Verify Pharmacy relationships")
            .satisfies(e -> assertThat(e.getSubscription()).as("check subscription").isEqualTo(actual.getSubscription()));
    }
}
