package com.pharmaresolve.medcom.domain;

import static com.pharmaresolve.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class WatchListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListAllPropertiesEquals(WatchList expected, WatchList actual) {
        assertWatchListAutoGeneratedPropertiesEquals(expected, actual);
        assertWatchListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListAllUpdatablePropertiesEquals(WatchList expected, WatchList actual) {
        assertWatchListUpdatableFieldsEquals(expected, actual);
        assertWatchListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertWatchListMapsIdRelationshipPersistedValue(WatchList entityToPersist, WatchList persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getPharmacy().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListAutoGeneratedPropertiesEquals(WatchList expected, WatchList actual) {
        assertThat(expected)
            .as("Verify WatchList auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListUpdatableFieldsEquals(WatchList expected, WatchList actual) {
        assertThat(expected)
            .as("Verify WatchList relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e ->
                assertThat(e.getCreated()).as("check created").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getCreated())
            )
            .satisfies(e -> assertThat(e.getLimit()).as("check limit").isEqualTo(actual.getLimit()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListUpdatableRelationshipsEquals(WatchList expected, WatchList actual) {
        // empty method
    }
}
