package com.pharmaresolve.medcom.domain;

import static com.pharmaresolve.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class WatchListLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListLogAllPropertiesEquals(WatchListLog expected, WatchListLog actual) {
        assertWatchListLogAutoGeneratedPropertiesEquals(expected, actual);
        assertWatchListLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListLogAllUpdatablePropertiesEquals(WatchListLog expected, WatchListLog actual) {
        assertWatchListLogUpdatableFieldsEquals(expected, actual);
        assertWatchListLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListLogAutoGeneratedPropertiesEquals(WatchListLog expected, WatchListLog actual) {
        assertThat(expected)
            .as("Verify WatchListLog auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListLogUpdatableFieldsEquals(WatchListLog expected, WatchListLog actual) {
        assertThat(expected)
            .as("Verify WatchListLog relevant properties")
            .satisfies(e -> assertThat(e.getUpdateType()).as("check updateType").isEqualTo(actual.getUpdateType()))
            .satisfies(e ->
                assertThat(e.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdateTime())
            )
            .satisfies(e -> assertThat(e.getUserAgent()).as("check userAgent").isEqualTo(actual.getUserAgent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListLogUpdatableRelationshipsEquals(WatchListLog expected, WatchListLog actual) {
        assertThat(expected)
            .as("Verify WatchListLog relationships")
            .satisfies(e -> assertThat(e.getWatchListItem()).as("check watchListItem").isEqualTo(actual.getWatchListItem()))
            .satisfies(e -> assertThat(e.getAppUser()).as("check appUser").isEqualTo(actual.getAppUser()))
            .satisfies(e -> assertThat(e.getPharmacy()).as("check pharmacy").isEqualTo(actual.getPharmacy()));
    }
}
