package com.pharmaresolve.medcom.domain;

import static com.pharmaresolve.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class WatchListItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemAllPropertiesEquals(WatchListItem expected, WatchListItem actual) {
        assertWatchListItemAutoGeneratedPropertiesEquals(expected, actual);
        assertWatchListItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemAllUpdatablePropertiesEquals(WatchListItem expected, WatchListItem actual) {
        assertWatchListItemUpdatableFieldsEquals(expected, actual);
        assertWatchListItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemAutoGeneratedPropertiesEquals(WatchListItem expected, WatchListItem actual) {
        assertThat(expected)
            .as("Verify WatchListItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemUpdatableFieldsEquals(WatchListItem expected, WatchListItem actual) {
        assertThat(expected)
            .as("Verify WatchListItem relevant properties")
            .satisfies(e ->
                assertThat(e.getDateAdded())
                    .as("check dateAdded")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getDateAdded())
            )
            .satisfies(e -> assertThat(e.getPriority()).as("check priority").isEqualTo(actual.getPriority()))
            .satisfies(e -> assertThat(e.getAlertEnabled()).as("check alertEnabled").isEqualTo(actual.getAlertEnabled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemUpdatableRelationshipsEquals(WatchListItem expected, WatchListItem actual) {
        assertThat(expected)
            .as("Verify WatchListItem relationships")
            .satisfies(e -> assertThat(e.getWatchList()).as("check watchList").isEqualTo(actual.getWatchList()))
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()));
    }
}
